name: vnphanquang:api docker build

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/com.vnphanquang-api
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/com.vnphanquang-api:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/com.vnphanquang-api:buildcache,mode=max
